### ISSUE TITLE
Enable building with GH Actions and hosting with GH Pages

### ISSUE THREAD

**Issue by endersonmaia** [endersonmaia/wolfi-os-riscv64-bootstrap#2]
It should be possible to build all artifacts from stages 1, 2 and 3 using GH Actions and host the `.apk` packages with GH Pages.

- [ ] #3
- [ ] Host stage1 packages at GH pages
- [ ] Build stage2 with GH Actions
- [ ] Host stage2 packages at GH pages
- [ ] Build stage3 with GH Actions
- [ ] Host stage3 packages at GH pages
